name: Kafka Load Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Start Stack
      run: docker compose up -d
      
    - name: Wait Ready
      run: |
        for i in {1..10}; do
          curl -f http://localhost:8000/health && break
          sleep 5
        done
      
    - name: Install Locust FULL
      run: |
        pip install "locust[full]"==2.29.0
        
    - name: Load Test
      run: |
        locust -f tests/locustfile.py \
          --headless --users 3 --spawn-rate 1 \
          --run-time 15s --host=http://localhost:8000 \
          --html=tests/report.html
        
    - name: Stop Stack
      run: docker compose down
      
    - uses: actions/upload-artifact@v4
      with:
        name: load-report
        path: tests/report.html
